<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>etl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		\#(?:
			    (?:define|if|for)\b \s* \(
			|\{ (?:define|if|for)\b \s* \(
		).*(?!\#\{?end).*$</string>
	<key>foldingStopMarker</key>
	<string>\#end\b|\#\{end</string>
	<key>keyEquivalent</key>
	<string>^@V</string>
	<key>name</key>
	<string>enjoy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.enjoy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\\[\!\#\$\\]</string>
			<key>name</key>
			<string>source.enjoy.embedded</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-number-sign</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.enjoy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\#\#\#).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=#\*)</string>
			<key>end</key>
			<string>(?&lt;=\-\-#|\-\-#\n)</string>
			<key>name</key>
			<string>source.enjoy.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#\-\-</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\-\-\#\n?</string>
					<key>name</key>
					<string>comment.block.documentation</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\#\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\#\n?</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.range.begin.java</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.java</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.continuation.range.java</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.java</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.range.end.java</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(-?\d+)(\.\.)(-?\d+)(\])</string>
					<key>name</key>
					<string>meta.definition.range.java</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.array.enjoy</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-brackets</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#array</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.array.enjoy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.enjoy</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.enjoy</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.begin.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.end.enjoy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						(\#) (?: 
							      \b(?:else|end)\b 
							|(\{) \b(?:else|end)\b (\})
						)</string>
					<key>name</key>
					<string>source.enjoy.embedded</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:define)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.module.macro.enjoy</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?&lt;=#define\()\s*([_a-zA-Z][-a-zA-Z0-9_]*)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:set)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.variable.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:if|for|switch|section|define)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:[a-zA-Z][-a-zA-Z0-9_]*)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				



				<dict>
					<key>begin</key>
					<string>((#)\b(?:[a-zA-Z][-a-zA-Z0-9_]*)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>directives-arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nest-parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.method.with-arguments.enjoy</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.enjoy</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.enjoy</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.enjoy</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.enjoy</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						 ((\# \@?   ) [a-zA-Z][-a-zA-Z0-9_]* \b) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)* ) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (\(\s*\))
					</string>
					<key>name</key>
					<string>source.enjoy.embedded</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
						 ((\# \@?   ) [a-zA-Z][-a-zA-Z0-9_]* \b) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)* ) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (\()\s* 
					</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.method.with-arguments.enjoy</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.enjoy</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.enjoy</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.enjoy</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.enjoy</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
						 \# \!? \(
					</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.enjoy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.enjoy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.enjoy.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.function-call.method.with-arguments.enjoy</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.enjoy</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.arguments.enjoy</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\w+)(\(\))</string>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\()</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.function-call.method.with-arguments.enjoy</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.enjoy</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.arguments.begin.enjoy</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.arguments.end.enjoy</string>
								</dict>
							</dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function-arguments</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>punctuation.separator.parameters.enjoy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.method.with-arguments.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.enjoy</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.enjoy</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.enjoy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
					\s* (\))( ( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (\()\s* )
					</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nest-parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|switch|for|else|case|end|continue|define|section)\b</string>
					<key>name</key>
					<string>keyword.control.enjoy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(set|number|date|include|render|push|return|break|escape|reset)\b</string>
					<key>name</key>
					<string>keyword.enjoy</string>
				</dict>
			</array>
		</dict>
		<key>nest-brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-parens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nest-curly</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-parens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nest-parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-parens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.assignment.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\-|\+\+)</string>
					<key>name</key>
					<string>keyword.operator.increment-decrement.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;&amp;|\|\|)</string>
					<key>name</key>
					<string>keyword.operator.logical.java</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.enjoy</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.enjoy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#directives</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\#\(</string>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>source.enjoy.embedded.source</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.enjoy</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\'</string>
							<key>name</key>
							<string>constant.character.escape.enjoy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.enjoy</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.enjoy</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.enjoy</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.enjoy</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.enjoy</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						 ((\# \@?   ) [a-zA-Z][-a-zA-Z0-9_]*) \b ( (?: (\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (?!\()
						|((\# \@? \() [a-zA-Z][-a-zA-Z0-9_]*) \b ( (?: (\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) ((\)))
					</string>
					<key>name</key>
					<string>source.enjoy.embedded</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.enjoy</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.enjoy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.enjoy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.enjoy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						 (\# \@?   ) [a-zA-Z][-a-zA-Z0-9_]* \b
						|(\# \@? \() [a-zA-Z][-a-zA-Z0-9_]* \b (\))
					</string>
					<key>name</key>
					<string>source.enjoy.embedded</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.enjoy</string>
	<key>uuid</key>
	<string>460426C7-D079-49DB-8E50-8E0B938644CA</string>
</dict>
</plist>
